name: Deploy

on:
  push:
    branches:
      - main

env:
  BUILD_DOCKER_REGISTRY: ghcr.io
  BUILD_DOCKER_IMAGE: ghcr.io/${{ github.repository }}
  BUILD_DOCKER_CONTEXT: '.'
  APP_NAME: ${{ github.event.repository.name }}

jobs:
  deploy:
    name: 'Build and push to docker registry'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64
      - id: version
        shell: bash
        run: echo "version=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/build-push-action@v3
        with:
          context: '.'
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            ${{ inputs.build-args }}
            VERSION=${{steps.version.outputs.version}}
          tags: ${{ env.BUILD_DOCKER_IMAGE }}:${{ steps.version.outputs.version }},${{ env.BUILD_DOCKER_IMAGE }}:latest
          cache-from: type=registry,ref=${{ env.BUILD_DOCKER_IMAGE }}:latest
          cache-to: type=inline
      - uses: vlaurin/action-ghcr-prune@main
        with:
          container: multi-arch-testing
          keep-last: 1
          token: ${{ secrets.GH_TOKEN }}
